import React from "react";
import Navbar from "@/components/home/Navbar";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Footer from "@/components/footer/Footer";

function GlobalLayout({ children, customClass }) {
  const { data: session } = useSession();
  let className = customClass ? customClass : "globalContainer";
  return (
    <>
      <Head>
        <title>Kick Store Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar session={session} />
      <main className={className}>{children}</main>
      {/* <Footer/> */}
    </>
  );
}

export default GlobalLayout;
